### ISSUE TITLE
create database for the plants #2

### ISSUE THREAD

**Issue by NicoleLinde** [NicoleLinde/MyCapstoneProject#1]
**Story**
As a user I want to be able to see the plants that have a value for pollinators or birds.

**Description**

In order to get just the information that meet the requirements of this app for the user it is important to have a database that holds the plants saved and enriched with the necessary information.

**Complexity: XL**

**Acceptance Criteria**

- [x] Database is functioning

- [x] Database can receive and store data in correct format

- [x] plants are stored in the database

**Tasks**

- [x] Create a feature branch

- [x] Test the server POST and GET functions on the database with Postman

- [x] Enter the plants into the database
