### ISSUE TITLE
create a Server for the plants database

### ISSUE THREAD

**Issue by NicoleLinde** [NicoleLinde/MyCapstoneProject#2]
**Story**
As a user I want to be able to see the plants that have a value for pollinators or birds.

**Description**

Create a server between the frontend and the backend where the plants with the corresponding information can be fetched from.

**Complexity:** S

**Acceptance criteria**

- [x] sorted plants can be retrieved from the database

**Tasks**

- [x] Create a feature branch

- [x] Install Express, Mongoose and dotenv

- [x] Instantiate the server and create the routes

- [x] implement POST and GET commands for the server

- [x] implement the Mongoose data scheme for the Database
