### ISSUE TITLE
Integrate data from backend to frontend

### ISSUE THREAD

**Issue by NicoleLinde** [NicoleLinde/MyCapstoneProject#3]
**Story**
As a user I want to be able to see the plants that have a value for pollinators or birds.

**Description**

The app should be able to fetch data from my database via the API and display the plantcards in the app.

**Complexity:** S

**Acceptance Criteria**

- [x] App is able to fetch information and display it

- [x] plants are displayed

**Tasks**

- [x] Create a feature branch

- [x] Create the fetch logic in the app and store into a useState

- [x] Display plants from database in the app
