### ISSUE TITLE
create a Searchbar for the plants

### ISSUE THREAD

**Issue by NicoleLinde** [NicoleLinde/MyCapstoneProject#4]
**Story**
As a user I want to be able to search for certain plants and find out if they have a value for pollinators or birds.

**Description**

Create a searchbar that filters the requested plant from the database.

**Complexity:** XL

**Acceptance criteria**

- [x] click on search Icon opens the searchbar

- [x] user can search for plants

- [x] user sees recommended search results while typing

- [x] selecting a search result leads to the result page

**Tasks**

- [x] Create a feature branch

- [x] add searchbar- component

- [x] implement search logic

- [ ] add style-guidist component for searchbar
