### ISSUE TITLE
create Card Components for the plants

### ISSUE THREAD

**Issue by NicoleLinde** [NicoleLinde/MyCapstoneProject#5]
**Story**

As a user I want to see the plant's information clearly so that I can find the details on first sight.

**Description**

The plants should be displayed on a card with additional information.

**Acceptance criteria**

- [x] one card per plant

- [x] user can see use for certain animal

- [x] user can add plant to favorites

**Complexity:** S

**Tasks**

- [x] new feature branch plant-card

- [x] add card component

- [x] add favorite-bookmark

- [x] implement bookmark-logic

- [ ]  add style-guidist for card component
