### ISSUE TITLE
Navbar

### ISSUE THREAD

**Issue by NicoleLinde** [NicoleLinde/MyCapstoneProject#6]
**Story**

As a user I want to be able to navigate easily so that I can have access to my favorites, Calendar and Home on one click.

**Description**
User is able to switch between the Home, Favorites and Calendar page via the navigation bar.

**Acceptance Criteria**

- [x]  click on icon to get access to extra pages

- [ ] icons appear active when clicked

- [ ]  icons have different appearance when hovered

**Complexity:** S

**Tasks**

- [x] create navbar-branch

- [x] add navbar- component

- [x] implement Links

- [ ] implement hover and active- Style
